server {
    listen 80;
    listen [::]:80;
    server_name jasasuruhjepara.isacool.my.id;

    root /var/www/jasasuruhjepara;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|svg|png|jpg|jpeg|gif|webp|ico|js)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
